# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rncourse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rncourse

  target 'rncourse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rncourseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rncourse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rncourse-tvOS

  target 'rncourse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
